apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-app
  labels:
    app: inventory-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: your-registry/inventory-management:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: db-password
        - name: SHOPIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: shopify-api-key
        - name: SENDLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: sendle-api-key
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5